info: {}
name: pad_array_Ppad_S150_150_a72008f6
settings:
  centered_ports: false
  columns: 6
  layer: MTOP
  pad: pad
  port_orientation: 0
  rows: 1
  size:
  - 100
  - 100
  spacing:
  - 150
  - 150
