info:
  components: 80
name: cutback_component_CFtap_6163df90
settings:
  bend180: Fbend_euler_Mgdsfactorypcomponentspbend_euler_SA180
  cols: 4
  component: Ftaper_from_csv_Mgdsfactorypcomponentsptaper_from_csv_SFtaper_strip_0p5_3_36pcsv
  cross_section: strip
  mirror: false
  mirror1: false
  mirror2: false
  port1: o1
  port2: o2
  rows: 5
  straight: straight
