info: {}
name: pad_array_Ppad_S150_150_77fd89b7
settings:
  centered_ports: false
  columns: 6
  layer: MTOP
  pad: pad
  port_orientation: 270
  rows: 1
  size:
  - 100
  - 100
  spacing:
  - 150
  - 150
