info: {}
name: pad_array_Ppad_S150_150_545fcaa3
settings:
  centered_ports: false
  columns: 1
  layer: MTOP
  pad: pad
  port_orientation: 180
  rows: 3
  size:
  - 100
  - 100
  spacing:
  - 150
  - 150
