info:
  length: 10
  width1: 0.5
  width2: 0.5
name: taper_L10_W0p5_WNone_PN_78a0ca3a
settings:
  cross_section: metal_routing
  length: 10
  port_names:
  - e1
  - e2
  port_types:
  - electrical
  - electrical
  width1: 0.5
  with_bbox: true
  with_two_ports: true
